baseURL = "https://rafasf.github.io"
languageCode = "en-us"
title = "Notes and Thoughts"
theme = "cocoa"

author = "Rafael Ferreira"
pygmentsuseclasses = true

publishDir = "docs/"

[params]
author = "Rafael Ferreira"
description = "collection of notes and possibly some thoughts"
github = "//github.com/rafasf"
linkedin = "//linkedin.com/in/rafaelsf/"
twitter = "//twitter.com/techzin"
hightlightjs = true
noshowreadtime = false
gravatar = "ed42dd1e94bd5f1f08f0981c5c047d6f"
