version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:0.28
    steps:
      - checkout
      - run:
          name: Build
          command: HUGO_ENV=production hugo -v
      - run:
          name: Deploy
          command: aws s3 sync ./public s3://rafasf.com/ --delete
