version: 2

jobs:
  build:
    docker:
      - image: cibuilds/hugo:0.28
    working_directory: ~/page
    steps:
      - checkout
      - attach_workspace:
          at: ~/page
      - run:
          name: Build
          command: HUGO_ENV=production hugo -v
      - persist_to_workspace:
          root: .
          paths: public
  deploy:
    machine: true
    working_directory: ~/page
    steps:
      - attach_workspace:
          at: ~/page
      - run:
          name: Deploy
          command: aws s3 sync ./public s3://rafasf.com/ --delete --acl public-read

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
