version: 2

jobs:
  build:
    docker:
      - image: cibuilds/hugo:0.28
    steps:
      - checkout
      - run:
          name: Build
          command: HUGO_ENV=production hugo -v
      - save_cache:
          key: v1-assets-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - public
  deploy:
    machine: true
    steps:
      - restore_cache:
          key: assets-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Deploy
          command: aws s3 sync ./public s3://rafasf.com/ --delete

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
