version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.15

jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/page
    steps:
      - checkout
      - attach_workspace:
          at: ~/page
      - run:
          name: Install dependencies
          command: git submodule sync && git submodule update --init
      - run:
          name: Build
          command: HUGO_ENV=production hugo -v
      - persist_to_workspace:
          root: .
          paths:
            - public
  deploy:
    docker:
      - image: "cimg/python:3.6"
    working_directory: ~/page
    steps:
      - attach_workspace:
          at: ~/page
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          from: public
          overwrite: true
          to: "s3://rafasf.com/"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
